BEGIN TRANSACTION [Tran1]
BEGIN TRY
	
	-- Your SQL Code Here
      
    COMMIT TRANSACTION [Tran1]
	SELECT 'Success' as RESULT
END TRY

BEGIN CATCH
    ROLLBACK TRANSACTION [Tran1]
	SELECT 'ERROR! Rolledback.' as RESULT
END CATCH  
